#!/bin/bash
#PBS -l walltime=00:05:00
for(i=1;i<=20;i++){
#PBS -l nodes=i:ppn=5
}
#PBS -W group_list=newriver
#PBS -q normal_q
#PBS -A CMDA3634

#Change to the directory from which the job was submitted
cd $PBS_O_WORKDIR

#Load modules
module purge; module load gcc mvapich2

#May not be necessary if the program is already built
mpicc mandelbrot.c -o mandelbrot

#Run
echo "Run mandlebrot with $PBS_NP cores"
mpiexec -n $PBS_NP ./mandelbrot

exit;

